apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secrets
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT 密钥
  JWT_SECRET: {{ .Values.app.jwtSecret | b64enc | quote }}
  
  # 数据库配置
  DB_DSN: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=%s" .Values.database.user .Values.database.password .Values.database.host .Values.database.port .Values.database.name .Values.database.sslMode | b64enc | quote }}
  
  # Redis 配置
  REDIS_ADDR: {{ printf "%s:%d" .Values.redis.host .Values.redis.port | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  REDIS_DB: {{ .Values.redis.db | toString | b64enc | quote }}
  
  # 支付配置
  PAYMENT_APP_ID: {{ .Values.payment.appId | b64enc | quote }}
  PAYMENT_PRIVATE_KEY: {{ .Values.payment.privateKey | b64enc | quote }}
  PAYMENT_PUBLIC_KEY: {{ .Values.payment.publicKey | b64enc | quote }}
  PAYMENT_IS_PRODUCTION: {{ .Values.payment.isProduction | b64enc | quote }}
  
  # 阿里云配置
  ALIYUN_ACCESS_KEY_ID: {{ .Values.aliyun.accessKeyId | b64enc | quote }}
  ALIYUN_ACCESS_KEY_SECRET: {{ .Values.aliyun.accessKeySecret | b64enc | quote }}
  ALIYUN_SMS_SIGN_NAME: {{ .Values.aliyun.sms.signName | b64enc | quote }}
  ALIYUN_SMS_TEMPLATE_CODE: {{ .Values.aliyun.sms.templateCode | b64enc | quote }} 