# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Image registry
  registry: "harbor.polesnet.com"
  # Image repository
  repository: "polesnet/polesnet-api"
  # Image tag, default to the chart appVersion
  tag: ""
  # Image pull policy
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
app:
  port: 8080
  jwtSecret: "my-secret-key"

# Database configuration
database:
  # Use Kubernetes Service name as hostname
  host: "postgres-service"
  port: 5432
  name: "polesnet"
  user: "postgres"
  password: "postgres"
  sslMode: "disable"
  # Optional configuration
  maxOpenConns: 25
  maxIdleConns: 25
  connMaxLifetime: "1h"

# Redis configuration
redis:
  # Use Kubernetes Service name as hostname
  host: "redis-service"
  port: 6379
  password: ""
  db: 0

# Payment configuration
payment:
  provider: "alipay"
  appId: ""
  privateKey: ""
  publicKey: ""
  isProduction: ""

# Aliyun configuration
aliyun:
  accessKeyId: ""
  accessKeySecret: ""
  sms:
    signName: ""
    templateCode: ""
